#' cube_abstract_trees
#'
#' The 23 trees with 8 vertices as an array of adjacency matrices
#'
#' @format An object of class \\code{array} of dimension 8 x 8 x 23.`
#'
#' @source Generated by Sage: graphs.trees(8)
"cube_abstract_trees"
