#' cube_span_trees
#'
#' The 384 spanning trees ot the cube as an array of adjacency matrices
#'
#' @format An object of class \\code{array} of dimension 8 x 8 x 384.
#'
#' @source Generated by Sage: \\code{oct = Graph("GrQHGs")
#' 			      oct.spanning_trees()}
"cube_span_trees"
