#' oct_span_trees
#'
#' The 384 spanning trees ot the octahedron as an array of adjacency matrices
#'
#' @format An object of class \\code{array} of dimension 6 x 6 x 384.
#'
#' @source Generated by Sage: oct = Graph("E\}lw")
#' 			      oct.spanning_trees()
"oct_span_trees"
