#' oct_abstract_trees
#'
#' The 6 trees with 6 vertices as an array of adjacency matrices
#'
#' @format An object of class \\code{array} of dimension 6 x 6 x 6.
#'
#' @source Generated by Sage: graphs.trees(6)
"oct_abstract_trees"
